
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yacqcturuylwyazkxzxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhY3FjdHVydXlsd3lhemt4enhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDMwOTksImV4cCI6MjA2MzY3OTA5OX0.fFZMaGd1hB6YemZw_H97Qo4Cs1IIeFvLgrhfAFO11fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Log para verificar a conexão
console.log('Supabase client initialized with URL:', SUPABASE_URL);
console.log('Checking Supabase connection...');

// Teste de conexão simples
supabase.from('profiles').select('count').then(({ data, error }) => {
  if (error) {
    console.error('Supabase connection error:', error);
  } else {
    console.log('Supabase connected successfully!');
  }
});
